[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "composer", "git", "unzip"]

[phases.build]
workingDirectory = "backend"
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan migrate --force",
  "php artisan db:seed --force",
  "mysql -h mysql.railway.internal -P 3306 -u root -pmCnEspvjatinzWZreSPggpZUPuKIkXrn railway -e 'SHOW TABLES;'"
]

[phases.start]
workingDirectory = "backend"
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
