[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "composer", "git", "unzip"]

[phases.build]
workingDirectory = "backend"
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.start]
workingDirectory = "backend"
cmd = "./railway-start.sh"
