[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "composer", "git", "unzip"]

[phases.build]
workingDirectory = "backend"
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.start]
workingDirectory = "backend"
cmd = 'sh -c "
  echo Running migrations... &&
  php artisan migrate --force &&
  echo Migrations complete &&
  echo Seeding database... &&
  php artisan db:seed --force &&
  echo Seeding complete &&
  echo Starting server... &&
  php artisan serve --host=0.0.0.0 --port=$PORT
"'
