[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "composer", "git", "unzip"]

[phases.build]
workingDirectory = "backend"
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.start]
workingDirectory = "backend"
cmd = """
echo '--- Starting Laravel app on Railway ---' && \
echo 'Running migrations...' && \
php artisan migrate --force && \
echo 'Migrations complete.' && \
echo 'Running seeders...' && \
php artisan db:seed --force && \
echo 'Seeders complete.' && \
echo 'Starting Laravel server...' && \
php artisan serve --host=0.0.0.0 --port=$PORT
"""
